import pytest
import time
import configparser
from pageobject.instagram import Login
from pageobject.dashbord import Dasbord
from utilites.log import Loger
confi = configparser.ConfigParser()
confi.read("utilites/input.properties")
@pytest.mark.usefixtures("setup")
class Test_insta(Loger):
    def test_login(self):
        log = self.getlogs()
        lo = Login(self.driver)
        do=Dasbord(self.driver)
        log.info("Test case start")
        time.sleep(3)
        lo.login(confi.get("userid","base_user"))
        log.info("Enter User name Sucessfully")
        time.sleep(3)
        lo.password(confi.get("passwo","base_pass"))
        log.info("Enter password sucessfully")
        time.sleep(1)
        lo.click()
        log.info("Login SucessFully")
        time.sleep(5)
        lo.notn()
        log.info("notification remove")
        time.sleep(5)
        do.message()
        log.info("click the message")
        time.sleep(3)
        do.send()
        log.info("click the send message button")
        time.sleep(3)
        do.search_username(confi.get("search","searchusername"))
        log.info("search the username")
        time.sleep(5)
        do.clic()
        log.info("click the username")
        time.sleep(5)
        do.chat()
        log.info("click the chat button")
        time.sleep(5)
        do.sendd(confi.get("message","welocome"))
        log.info("write message sucessfully")
        time.sleep(5)
        do.se()
        log.info("send message sucessfully")
        time.sleep(10)
        do.set()
        log.info("click seatting sucessfully")
        time.sleep(5)
        do.logout()
        log.info("logout sucessfully")
        time.sleep(1)

